### ISSUE TITLE
Add onBack prop

### ISSUE THREAD

**Issue by xylish7** [Pyozer/color_picker#12]
It would be greate if you can add a "onBack () {}" prop for MaterialColorPicker. I need to catch when the users press the back button and from what I see there is no option. Thank you!

**Comment by Pyozer** [comment]
Yeah it's a great idea !
I try to do it soon :)

**Comment by Pyozer** [comment]
Package updated to `v1.0.3`, onBack property has been added 🎉

**Comment by xylish7** [comment]
Nice! Thank you!
