### ISSUE TITLE
Programmatically set color?

### ISSUE THREAD

**Issue by wiradikusuma** [Pyozer/color_picker#19]
Inside `AlertDialog` I have `TypeAheadFormField` (from flutter_typeahead) and `MaterialColorPicker`:

	MaterialColorPicker(
		onMainColorChange: (ColorSwatch color) {
			this._myColor = color;
		},
		selectedColor: _myColor,
	)
	...
	onSuggestionSelected: (validColorInt) {
		this._textController.text = 'THE TEXT IS UPDATED';

		setState(() {
			this._myColor = Color(validColorInt); // BUT NOT THE PICKER
		});
	}

I want to change the picker's selected color when the user makes a selection. What do I miss?

**Comment by Pyozer** [comment]
Hello, sorry for the very late response.

I just tested through the code of the built-in example app, temporarily adding a MaterialColorPicket (without dialog), which ultimately does the same as your example and the color changes well during a setState.

I am closing this ticket, do not hesitate to re-open it if necessary.
