### ISSUE TITLE
Padding is missing at bottom

### ISSUE THREAD

**Issue by dario-digregorio** [Pyozer/color_picker#2]
Hello I really like your widget but I found a little problem:
Padding is missing the lower part of the widget therefore the shadows are cut
![image](https://user-images.githubusercontent.com/32966133/49407375-b1626b00-f758-11e8-9e93-9bba3eb8d584.png)
this is the part which is causing the problem:
`padding: const EdgeInsets.only(left: _kContainerPadding, right:  _kContainerPadding),`

By adding Padding to all parts the problem is fixed
`padding: const EdgeInsets.all(_kContainerPadding),`
![image](https://user-images.githubusercontent.com/32966133/49407466-043c2280-f759-11e8-8842-85db69267ecc.png)

**Comment by Pyozer** [comment]
Hi ! Sorry for the late response...

This issue has been already fixed, are you using the latest version ?
