### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by dna-f** [Pyozer/color_picker#26]
Hi, is Null safety migration on roadmap?
Thanks

**Comment by Arcturus5404** [comment]
Also wondering this!

**Comment by Pyozer** [comment]
Hi, sorry to not maintain this repo, not many time :/

I will migrate to null safety in next day ;)

**Comment by jacksonw765** [comment]
Any update on this? A lot of other plugins are dependent on this migration.

**Comment by saileshbro** [comment]
I can work on this issue.

**Comment by unknownaloy** [comment]
Any hope on migration to null-safety?

**Comment by apos37** [comment]
@Pyozer , it seems you are pretty busy. I hope things are going okay for you. Can you update us with a status on your plans to migrate? This is the only package left on my app that has not migrated yet. :(

**Comment by Pyozer** [comment]
@jacksonw765 @unknownaloy @mrgandy 
Sorry, not many time to maintain my projects :/

I've just publish v1.1.0 with null safety support.
Have a nice day ;)

**Comment by apos37** [comment]
Thank you @Pyozer ! 👍👍
